/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    kotlin("jvm") version "2.2.0" // Kotlin version
    kotlin("plugin.spring") version "2.2.0" // Kotlin version
    id("org.springframework.boot") version "3.5.3"
    id("io.spring.dependency-management") version "1.1.7" // from Gradle Plugin Portal
}

allprojects {
    group = "com.example"
    version = "0.1.0"
    repositories {
        mavenCentral()
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21 // Java Versionを指定
}

subprojects {
    apply(plugin = "org.jetbrains.kotlin.jvm")
    apply(plugin = "io.spring.dependency-management")
}
