/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "10.MultiModule"

// モジュール（サブプロジェクト）を列挙してビルドに含める
include("modules:core")
// include("modules:web")
// include("modules:security")
