/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    kotlin("jvm") version "2.2.0" // Kotlin version
    kotlin("plugin.spring") version "2.2.0" // Kotlin version
    id("org.springframework.boot") version "3.5.3"
    id("io.spring.dependency-management") version "1.1.7" // from Gradle Plugin Portal
    kotlin("plugin.jpa") version "2.2.0" // default constructerを回避する為に定義
}

repositories {
    mavenCentral()
}

// Spring Boot Webアプリに必要な依存関係を追加
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web") // Springboot Web Framework
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf") // Template Engine
    implementation("org.springframework.boot:spring-boot-starter-data-jpa") // JPAを使うため
    implementation("org.jetbrains.kotlin:kotlin-reflect") // Entity利用
    implementation("com.h2database:h2")
}

