version: '3.8'
services:
  app:
    build: .
    image: sqlite3-app
    container_name: sqlite3-app
    ports:
      - "8080:8080"
    volumes:
      - db:/app/data
    environment:
      - TZ=Asia/Tokyo
      - SPRING_PROFILES_ACTIVE=prod # application-prod.propertiesを使う
volumes:
  db:
    driver: local
