/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 */
plugins {
    id("org.springframework.boot")
}

dependencies {
    implementation("org.xerial:sqlite-jdbc:3.47.2.0") // SQLite JDBC Driver
    implementation("org.hibernate.orm:hibernate-community-dialects:6.6.18.Final") // Hibernateを利用する
    implementation("org.springframework.boot:spring-boot-starter-data-jpa") // Entityでjakarta.*を使うため
    implementation("org.jetbrains.kotlin:kotlin-reflect") // Kotlin Reflection
    implementation("org.springframework.boot:spring-boot-starter-validation") // バリデーションを利用するため
}
